const projects = {
    "ellevate-football": {
        title: "Ellevate Football",
        date: "Training Plans | 2024",
        cover: "./resources/projects/ellevate football.jpg",
        summary: "A personalised skill development system for young footballers on Ellevate Football.",
        background: "Ellevate Football is a mobile app designed to help young players improve their football skills. One of the biggest challenges users is knowing what to practice, how to measure their progress, and how to stay motivated. Users trained in isolation, making it difficult to track improvements over time. We recognized the need for a structured, data-driven, and gamified approach to skill development—one that not only assessed a player’s current abilities but also provided clear guidance on how to improve.<br><br> Before we built this feature, users engaged with Ellevate primarily through video-based training content without an adaptive learning component. There was no personalised skill tracking, progression system, or structured feedback loop, which meant players often lacked a sense of direction. The challenge was to create a feature that could accurately assess skill levels, recommend tailored training programs, and keep players engaged through an interactive experience. Additionally, we had to balance automation with human skill assessments while also incorporating expert feedback from coaches. To solve this, we introduced the Training Plans feature.",
        role: "As the <b>Head of Product</b>, I led the end-to-end development of this feature, managing a team of four engineers and one product designer. My responsibilities spanned <b>strategy, research, execution, and go-to-market planning</b>. I worked closely with stakeholders to define the product vision, collaborated with engineers to bring the feature to life, and led the marketing efforts to ensure a successful launch.",
        research: "The research phase was crucial to ensuring that the Training Plans feature would be engaging, effective, and commercially viable. We started with <b>user research surveys</b> to identify the pain points young footballers face when training alone. Many users expressed difficulty in knowing what to practice, tracking their progress, and staying motivated without a structured plan. To validate pricing models, we conducted a <b>Van Westendorp pricing survey</b>, which provided insights into how much users and their parents would be willing to pay for premium training plans.<br><br> To enhance engagement, we applied the <b>Octalysis gamification framework</b>, breaking down user motivation into core drivers such as accomplishment, social influence, and unpredictability. We also interviewed <b>coaches, football educators, and sports psychologists</b> to refine our training methodology, ensuring that the drills were structured for progressive skill development. Additionally, we studied various <b>sports science and learning frameworks</b> to understand the best ways to deliver feedback and structure skill improvement in a way that felt rewarding and achievable for young players.",
        planning: "Once we had a solid foundation from our research, we moved into the planning phase. We mapped out the <b>user journey</b>, from the moment a player decides to assess their skills to the point where they complete multiple training cycles and see improvements in their player card. We focused on ensuring a seamless </b>onboarding experience</b>, where users could quickly understand their skill levels through performing three benchmark drills that assessed six core football skills and feel motivated to start improving.<br><br> To make the training process engaging, we designed a <b>structured progression system</b>, where users could choose a skill, follow a personalised plan, and receive feedback at key milestones. Over time, their ratings would adjust, helping them track progress, climb leaderboards, and gain visibility among scouts. We defined key success metrics, such as <b>feature adoption, training completion rates, and skill rating improvements</b>, to measure the impact of the feature. Additionally, we carefully planned the <b>gamification strategy</b>, incorporating elements like leaderboards, achievements, and social sharing to keep users engaged.",
        development: "During development, I worked closely with engineers and designers to build an <b>intuitive and interactive</b> training experience. One of the major challenges was creating an <b>AI-assisted rating system</b> that could standardise drill performances and provide accurate skill assessments across coaches. We built an algorithm that factored in multiple performance metrics, allowing for dynamic adjustments to personalised training plans over time.<br><br> The feedback loop was another crucial component. We implemented a <b>hybrid system</b> where users would receive automated feedback based on predefined metrics but also had the option to get personalised insights from coaches. This ensured that users felt supported in their training journey while keeping the experience scalable. We also focused on making the <b>user interface highly visual and engaging</b>, leveraging animations and progress indicators to make skill progression feel rewarding.",
        launch: "For the launch, we executed a <b>multi-channel go-to-market strategy</b> to maximize adoption. A key component was partnering with <b>Premier League players</b> like Jack Grealish, Levi Colwill, and Oscar Bobb, as well as football YouTubers like ChrisMD and SV2. We created engaging <b>social media content, YouTube videos, and ads</b> featuring these players, reinforcing the idea that skill progression in the app could translate to real-world recognition.<br><br> In addition, we organized <b>live activations at the Junior Premier League</b> in the UK. At these events, players performed drills, received skill ratings, and had the chance to earn prizes based on their performance. This hands-on experience helped bridge the gap between digital and physical training, driving both engagement and word-of-mouth growth. Our launch efforts combined <b>organic community-building, influencer marketing, and paid media</b>, leading to strong initial adoption and high user engagement.<br><br> This feature introduced a <b>fundamental shift</b> in how users engaged with Ellevate Football, transforming it from a static training app into a <b>dynamic skill development platform</b> with personalized learning paths and competitive motivation.",
        image1: "./resources/projects/ellevate football.jpg",
        image2: "./resources/projects/ellevate football.jpg",
        image3: "./resources/projects/ellevate football.jpg",
        image4: "./resources/projects/ellevate football.jpg",
        alt: "Picture of the Ellevate Football project",
        takeaway1: "<b>Personalisation and gamification drive engagement</b> – Players were more motivated to improve when they saw their skill ratings evolve.",
        takeaway2: "<b>Influencer partnerships boost adoption</b> – Featuring well-known footballers and YouTubers helped establish credibility and excitement.",
        takeaway3: "<b>Live activations create deeper user engagement</b> – Physical events reinforced digital experiences and encouraged organic word-of-mouth growth.",
        next1: "<b>Refining the feedback mechanism</b> – Explore AI-driven insights to provide even more personalised training recommendations.",
        next2: "<b>Expanding monetization options</b> – Introduce premium training plans and exclusive content for subscribed users.",        
        next3: "<b>Enhancing the leaderboard experience</b> – Add competitive features like challenges and head-to-head comparisons to increase user retention."
    }, 

    "manchester-united": {
        title: "Manchester United",
        date: "D2C Monetization Strategy | 2021",
        cover: "./resources/projects/manutd.jpg",
        summary: "A global direct-to-consumer (D2C) strategy to unlock new revenue streams and fan engagement opportunities.",
        background: "With 1.1 billion fans and followers and 467 million global fans, Manchester United has one of the largest fanbases in world football. However, a significant portion of its revenue remains tied to match-day income, sponsorships, and traditional merchandise sales, leaving massive untapped potential in international markets and direct-to-consumer (D2C) monetization.<br><br> The club's existing digital and commercial infrastructure was fragmented, making it difficult to provide a seamless, engaging, and monetizable experience for fans worldwide. Additionally, Covid-19 accelerated the need for new digital revenue streams, as physical match-day attendance and retail sales were impacted. The challenge was to create a unified, scalable D2C strategy that could drive engagement, increase recurring revenue, and enhance Manchester United’s global brand presence outside of the UK.",
        role: "As a <b>consultant on Manchester United’s D2C strategy</b>, I led the research and strategic development for monetizing the club’s global fanbase. This involved conducting <b>competitive benchmarking, industry research, and market analysis</b> across football, other sports (NBA, NFL, IPL), entertainment (Disney, Netflix, Nike), and retail. I worked closely with key stakeholders at the club to <b>identify and prioritize revenue-generating opportunities</b> while ensuring alignment with Manchester United’s <b>brand identity and fan experience</b>.",
        research: "Our research focused on discovering the <b>best-in-class D2C strategies</b> across industries and assessing their applicability to Manchester United. We conducted:<br><br> 1. <b>Benchmarking</b> against clubs and leagues such as La Liga, Japanese J.League, NBA, NFL, UFC, and IPL, identifying D2C initiatives that successfully monetized fan engagement.<br><br> 2. <b>Market segmentation & localization</b> to understand the unique preferences of fans across different geographies, particularly in high-growth markets like India, Nigeria, and the US.<br><br> 3. <b>Financial modeling</b> to estimate potential revenue from various D2C initiatives, balancing short-term vs. long-term impact, fan engagement, operational complexity, and cost structure.<br><br> 4. <b>Stakeholder interviews</b> with internal teams (Media, Data & Analytics, Customer Acquisition) to align the strategy with Manchester United’s existing digital and commercial assets.",
        planning: "Based on our research, we developed a <b>comprehensive D2C roadmap</b>, focusing on initiatives that could maximize revenue while <b>enhancing fan engagement</b>. Our <b>tiered membership model</b> became the foundation for all offerings, integrating:<br><br> 1. <b>Digital products</b>: A revamped Man Utd app with premium content, live interactions, and exclusive fan-led features.<br><br> 2. <b>Physical experiences</b>: Man Utd pop-up hubs in key cities worldwide to create localized matchday experiences and increase direct fan interaction.<br><br> 3. <b>E-commerce expansion</b>: A localized and customized retail platform, ensuring global fans had access to tailored merchandise, payment options, and fulfillment services.<br><br> 4. <b>Masterclass programs</b>: Exclusive multi-part courses featuring players, coaches, nutritionists, and sports scientists, offering fans an immersive learning experience.<br><br> 5. <b>VR/AR-powered stadium experiences</b>: Creating virtual Old Trafford experiences in international markets using AR/VR to replicate live matchday atmospheres.<br><br> We structured our <b>implementation roadmap</b> into short-term and long-term initiatives, ensuring that revenue opportunities could be realized <b>within five years</b> while gradually <b>expanding digital infrastructure and operational capabilities</b>.",
        development: "Executing this strategy required Manchester United to <b>streamline its internal digital ecosystem and enhance its technological capabilities</b>. We recommended:<br><br> 1. <b>A unified fan membership system</b> integrating MUTV, the Man Utd app, e-commerce, and digital content.<br><br> 2. <b>Localized market presence</b> by setting up regional hubs and partnerships to drive engagement in high-growth markets.<br><br> 3. <b>Cross-functional alignment</b> between media, retail, and club marketing to create a consistent, high-quality D2C experience.<br><br> To support these initiatives, we outlined the <b>necessary investments in content creation, digital platform enhancements, and international infrastructure</b> while optimizing costs through strategic outsourcing and licensing partnerships.",
        launch: "Our projections estimated that <b>a global D2C membership model priced at ~£5/month</b> could generate <b>£45M in annual recurring revenue by Year 5</b>, with a <b>20% year-on-year subscriber growth</b>. Additional monetization streams, such as masterclasses, VR matchday experiences, and localized e-commerce, had the potential to contribute <b>hundreds of millions in incremental revenue</b> while significantly increasing daily active engagement (DAU) across digital platforms.",
        image1: "./resources/projects/manutd.jpg",
        image2: "./resources/projects/manutd.jpg",
        image3: "./resources/projects/manutd.jpg",
        image4: "./resources/projects/manutd.jpg",
        alt: "Picture of the Manchester United project",
        takeaway1: "<b>Transformation of business model</b> - from relying heavily on sponsorships and match-day revenue to a sustainable, fan-driven digital economy.",
        takeaway2: "<b>Establishing deeper fan relationships</b> - through an always-on, interactive, and localized engagement model.",
        takeaway3: "<b>Expanding commercial footprint</b> - in key international markets, creating new avenues for sponsorships, partnerships, and content monetization.",
        next1: "<b>Implementation of the unified membership model</b> - integrating all digital products under a single-tiered system.",
        next2: "<b>Expansion of localized Man Utd hubs</b> - in high-potential regions like the US, India, and Nigeria.",        
        next3: "<b>Investment in emerging technologies</b> - such as VR stadium experiences and fan-led digital engagement tools, to future-proof the club’s revenue strategy."
    },

    "macys": {
        title: "Macy's",
        date: "Lean Labs | 2018",
        cover: "./resources/projects/macys.jpg",
        summary: "Driving data-driven decision-making to enhance eCommerce performance using A/B Tests.",
        background: "Macy’s, one of the largest retail brands in the US, needed to optimize its eCommerce platform and mobile apps to increase conversion rates, average order value (AOV), and total revenue. Despite having millions of daily visitors, many product and UX decisions were being made based on intuition rather than data. There was no formalized A/B testing framework, leading to missed opportunities and inefficient product investments.<br><br> To address this, I was brought in as a Senior Consultant - Product Management and Analytics to establish a scalable, data-driven experimentation process. Over three years, I led a team of eight specialists, ran 160+ A/B tests, and embedded decision-driven experimentation across 12-15 product teams. Our efforts directly increased order conversion by 8%, AOV by 13%, and contributed $20M+ in annual revenue growth.",
        role: "As the <b>lead for A/B testing at Macy’s</b>, I worked across <b>12-15 product teams</b>, including <b>Search, Checkout, Product View, Add to Bag, Wishlist, and Product Recommendations</b>, to integrate <b>experiment-driven decision-making</b> into their workflows. My responsibilities included:<br><br> 1. <b>Establishing a governance structure</b>, including p-value thresholds, sample size calculations, traffic randomization rules.<br><br> 2. <b>Defining success metrics</b> and statistical significance criteria to ensure reliable results. <br><br> 3. <b>Managing end-to-end experiment execution</b>, from research and hypothesis formulation to development, launch, and analysis.",
        research: "Every experiment started with <b>data-driven problem identification</b>. We analyzed user behavior through <b>SQL queries</b>, looking at drop-off points and inefficiencies across the site and app. We examined <b>NPS scores, CSAT surveys, and user interviews</b> to capture customer sentiment and frustrations. Session replays and heatmaps provided qualitative insights into areas where users struggled. From this data, we <b>uncovered patterns and pain points</b>, such as high cart abandonment rates, friction in the checkout process, and low engagement with product recommendations.<br><br> Once key issues were identified, we <b>formulated clear hypotheses</b> using the null and alternative framework. For example, if a high cart abandonment rate was detected, a hypothesis might be:<br><br> 1. <b>Null Hypothesis (H₀)</b>: Removing extra form fields in checkout will have no impact on conversion rates.<br> 2. <b>Alternative Hypothesis (H₁)</b>: Removing extra form fields will increase checkout conversion rates by at least 5%.<br><br> By framing experiments in this structured way, we ensured that every test had a <b>clear objective and measurable success criteria</b> before moving forward.",
        planning: "With a well-defined hypothesis, we moved into the planning phase, where we designed controlled experiments that could yield <b>statistically valid and actionable insights</b>. This involved defining <b>primary and secondary success metrics</b>, such as conversion rate, engagement time, and AOV, while also monitoring overall business health indicators to prevent unintended negative impacts.<br><br> We ran <b>pre-power tests</b> to calculate the required sample size, ensuring that each test had enough data to produce statistically significant results. <b>Traffic was then randomly allocated</b> between control and test groups to maintain comparability and eliminate biases. <b>Test variations were carefully designed</b>, ensuring that UI/UX changes were distinct enough to be measurable while maintaining a seamless experience for users.<br><br>Throughout this process, collaboration was key. I worked closely with product managers, designers, and engineers across multiple teams to align on test objectives and ensure that each experiment fit into Macy’s broader <b>business goals and product roadmap</b>.<br><br> Each A/B test was mapped into a <b>structured experimentation roadmap</b>, ensuring that Macy’s had a continuous pipeline of <b>validated insights driving product enhancements</b>.",
        development: "Once an experiment was planned, we collaborated with engineering teams to <b>build the necessary test variations</b>. This often required working across different components of the Macy’s digital ecosystem, ensuring that changes were accurately implemented and seamlessly integrated into the customer experience. A strong <b>QA process</b> was in place to identify any potential bugs or inconsistencies before launch.<br><br> To enable real-time monitoring, we built <b>custom analytics dashboards</b>, allowing us to track key metrics as the test progressed. These dashboards provided insights into user behavior, engagement, and revenue impact, making it easier to react quickly if any anomalies were detected. The engineering team also worked to minimize <b>performance trade-offs</b>, ensuring that tests did not introduce latency or disrupt the shopping experience.",
        launch: "Once an A/B test was live, we closely monitored its performance, collecting data in real time and ensuring that our <b>sample size thresholds were met</b> before drawing conclusions. Using <b>two-tailed t-tests</b>, we determined whether the observed changes were <b>statistically significant</b>. If the test showed a <b>clear positive impact</b>, we rolled out the variation to all users. If the results were <b>inconclusive</b>, we analyzed the findings, iterated on the approach, and ran follow-up experiments. If the test had <b>negative effects</b>, we quickly rolled it back, ensuring no long-term harm to the business.<br><br> The success of this structured experimentation approach was evident in the results. Beyond the financial gains, our work embedded a culture of <b>data-driven decision-making</b>, ensuring that every major change at Macy’s was backed by rigorous testing and real user insights.",
        image1: "./resources/projects/macys.jpg",
        image2: "./resources/projects/macys.jpg",
        image3: "./resources/projects/macys.jpg",
        image4: "./resources/projects/macys.jpg",
        alt: "Picture of the Macy's project",
        takeaway1: "<b>Data-driven decision-making transformed Macy’s eCommerce roadmap</b>, reducing reliance on intuition and assumptions.",
        takeaway2: "<b>A/B testing delivered measurable financial impact</b>, increasing order conversion by 8%, AOV by 13%, and generating $20M+ in incremental revenue annually.",
        takeaway3: "<b>The structured experimentation framework improved long-term user experience</b>, leading to higher engagement, retention, and customer satisfaction.",
        next1: "<b>Scaling the A/B testing function</b> – Expanding to include AI-driven personalization tests and real-time pricing experiments.",
        next2: "<b>Automating experiment analysis</b> – Implementing ML-powered anomaly detection for faster insights.",        
        next3: "<b>Embedding A/B testing deeper into Macy’s strategy</b>, ensuring that every new feature is validated through rigorous experimentation before launch."
    },

    "vested-finance": {
        title: "Vested Finance",
        date: "Transfer Funds | 2020",
        cover: "./resources/projects/vested finance.jpg",
        summary: "Automating fund transfers to remove friction for Indian investors in the US stock market.",
        background: "Vested Finance is a platform that enables Indian investors to seamlessly invest in the US stock market. To begin investing, users must transfer funds from their Indian bank accounts to our brokerage partner, DriveWealth. However, this process was highly manual, cumbersome, and time-consuming. Users had to visit their bank in person, fill out remittance forms, and rely on the bank to process their transactions. The experience was frustrating—users struggled with appointment delays, long wait times, form-filling errors, and bureaucratic inefficiencies.<br><br> This friction directly impacted Vested Finance’s business. Many users abandoned the process before transferring funds, while others transferred money less frequently than they would have if the process were easier. We realized that the success of our platform hinged on making fund transfers effortless. Without a smooth onboarding and funding experience, investors wouldn’t reach the stage where they could actively trade.",
        role: "As a <b>Product Manager and the first product hire</b> at Vested Finance, I was responsible for researching, designing, and launching the new Transfer Funds feature. I worked closely with <b>engineering, banking partners, compliance teams, and customer support</b> to develop a seamless and compliant solution. My role spanned <b>strategy, user research, product development, partnerships, and go-to-market execution</b>.",
        research: "We began by thoroughly <b>investigating the existing fund transfer process</b>, breaking it down into distinct steps: filling out the remittance form, submitting it to the bank, processing, transfer initiation, and finally, crediting the amount to the brokerage account. To understand user pain points, we conducted <b>user interviews, surveys, and app feedback analysis</b>. Observational studies helped us witness firsthand how investors struggled with appointment delays, incorrect form submissions, and unclear status updates on their transactions.<br><br> To build an effective solution, we <b>engaged directly with major Indian banks</b>, understanding their internal workflows, the exact details they required for processing remittances, and their preferred submission formats. We also explored the possibility of automating approvals and streamlining bank-side processes. By the end of this research phase, we had <b>mapped out the most common user struggles and regulatory constraints</b>, giving us a clear foundation for the next phase.",
        planning: "Armed with insights from users and banks, we outlined a step-by-step strategy to build a <b>dual-customer solution</b> — one that worked for both investors and banks. A major priority was eliminating manual errors by <b>auto-filling remittance forms</b> using KYC data that was already collected during user onboarding. This would not only remove the need for users to fill out the form themselves but also prevent incorrect submissions that led to bank rejections. We also planned to <b>integrate directly with banks</b> wherever possible to accelerate processing times and reduce manual intervention.<br><br> Given the complexity of international remittances, we opted for a <b>phased rollout strategy</b>. Our initial MVP allowed users to enter their bank details and transfer amount directly into the app. Once they authorized us to facilitate the transfer on their behalf, our customer support team manually filled out the remittance form and submitted it to the bank. This approach allowed us to <b>validate demand, usability, and compliance before scaling to full automation</b>. We also considered transparency a key factor in improving the user experience. To address this, we planned to introduce a <b>transfer progress tracker</b> within the app, giving users visibility into where their funds were in the process.",
        development: "Once we had validated the concept with the MVP, we focused on building a <b>fully automated system</b>. The first step was <b>integrating Plaid’s API</b> into the app, allowing users to choose their bank, enter transfer details, and initiate the process without leaving the platform. On the backend, the system <b>auto-filled the remittance form</b> using pre-collected KYC data and <b>sent a digital copy to the banks for processing</b>. For banks with more advanced digital infrastructure, we worked on <b>direct API integrations</b>, enabling real-time fund transfer initiation.<br><br> Simultaneously, we built out <b>user-facing enhancements</b> such as a progress tracker that displayed the status of each transfer, addressing a major source of anxiety for investors. <b>Compliance was a critical component</b>, and we worked closely with regulatory and legal teams to ensure the new system <b>adhered to RBI guidelines</b>. Throughout this phase, we also documented the entire process, <b>creating FAQs, support articles, and in-app guides</b> to help users understand how the feature worked and why it was safe.",
        launch: "The <b>rollout was executed in multiple stages</b> to minimize risk and gather real-world feedback. We <b>began with the MVP</b>, where users manually input transfer details, and our customer support team handled form submission on their behalf. This allowed us to <b>validate the feature's necessity and usability</b> before automating it further.<br><br> As we gained confidence in the process, we introduced <b>automated form submission</b>, significantly reducing manual intervention and transfer delays. <b>The final stage involved full automation</b>, with direct integrations into select banks that enabled near-instant processing. To drive awareness, we positioned this feature as a key differentiator in <b>marketing campaigns, social media promotions, and advertisements</b>. Customer service teams were also trained to introduce the feature to new users during onboarding, ensuring maximum adoption. The combination of improved user experience, increased transparency, and automation <b>resulted in significant growth in both first-time deposits and repeat transfers</b>.",
        image1: "./resources/projects/manutd.jpg",
        image2: "./resources/projects/manutd.jpg",
        image3: "./resources/projects/manutd.jpg",
        image4: "./resources/projects/manutd.jpg",
        alt: "Picture of the Vested Finance project",
        takeaway1: "<b>Removing friction in transfers is critical</b>. Our solution led to a 20% increase in funded accounts and 10x rise in repeat deposits.",
        takeaway2: "<b>A phased rollout helped mitigate risks</b>. Allowed us to test usability and refine the experience before scaling.",
        takeaway3: "<b>Building for both users and banks ensured long-term success</b>. Working with banks, we ensured alignment with their requirements, leading to smoother approvals and processing.",
        next1: "<b>Expanding bank integrations</b> – Working with more Indian banks to enable instant transfers across a wider user base.",
        next2: "<b>Introducing instant deposits</b> – Exploring fintech partnerships to allow real-time deposits via UPI and other payment methods.",        
        next3: "<b>Optimizing fund withdrawal processes</b> – Improving the withdrawal experience to ensure users can seamlessly cash out investments."
    }
 
};


    const projectKey = new URLSearchParams(window.location.search).get('project');
    if (projectKey && projects[projectKey]) {
        const project = projects[projectKey];
        document.title += ' ' + project.title

        document.getElementById('case-title').textContent = project.title;
        document.querySelector('.case-summary h3').textContent = project.date
        document.querySelector('.case-summary p').textContent = project.summary
        document.querySelector('.case-summary img').src = project.cover
        document.querySelector('.case-summary img').alt = project.title

        document.querySelector('.case-background p').innerHTML = project.background
        document.querySelector('.role p').innerHTML = project.role

        document.getElementById('research').innerHTML = project.research;
        document.getElementById('planning').innerHTML = project.planning;
        document.getElementById('development').innerHTML = project.development;
        document.getElementById('launch').innerHTML = project.launch;

        document.querySelector('.study-image img:nth-child(1)').src = project.image1
        document.querySelector('.study-image img:nth-child(1)').alt = project.alt
        document.querySelector('.study-image img:nth-child(2)').src = project.image2
        document.querySelector('.study-image img:nth-child(2)').alt = project.alt
        document.querySelector('.study-image img:nth-child(3)').src = project.image3
        document.querySelector('.study-image img:nth-child(3)').alt = project.alt
        document.querySelector('.study-image img:nth-child(4)').src = project.image4
        document.querySelector('.study-image img:nth-child(4)').alt = project.alt

        document.querySelector('.takeaways li:nth-child(1)').innerHTML = project.takeaway1
        document.querySelector('.takeaways li:nth-child(2)').innerHTML = project.takeaway2
        document.querySelector('.takeaways li:nth-child(3)').innerHTML = project.takeaway3
        document.querySelector('.next-steps li:nth-child(1)').innerHTML = project.next1
        document.querySelector('.next-steps li:nth-child(2)').innerHTML = project.next2
        document.querySelector('.next-steps li:nth-child(3)').innerHTML = project.next3
    }

   
